#!/bin/bash
#
# https://github.com/rarmknecht/utilities/blob/master/mpc_toggle
#
# Filename: mpc_toggle
# Desc: Uses mpc to toggle mpd between play & pause states. (Used with i3 key binding)
# Date: 2013.04.14
#

state=$(mpc --port 6601 | grep playing| wc -l)

# 0 is stopped
# 1 is playing

if [[ $state = 1 ]]; then
	mpc --port 6601 pause >> /dev/null
else
	mpc --port 6601 play >> /dev/null
fi
exit 0
